### ISSUE TITLE
将窗口从主屏幕拖入扩展屏幕后，鼠标在窗口中形状变成拉伸的箭头，不能执行点击事件，只能执行拉伸操作

### ISSUE THREAD

**Issue by be-water-myFriend** [canpool/qxframeless#1]

**Comment by canpool** [comment]
感谢你的反馈。

这种现象之前在高dpi屏幕到低dpi屏幕移动后，由于鼠标pos未转换导致的，后来已修复。

请问你的屏幕是什么情况，补测如下：

测试环境：Qt 5.14.2，两块1920*1080屏幕
- 两块屏幕缩放100%，移动正常
- 一块屏幕缩放100%，一块屏幕缩放150%，移动正常


会不会和Qt版本有关系？

**Comment by canpool** [comment]
长时间不响应，关闭本issue

**Comment by be-water-myFriend** [comment]
https://github.com/canpool/qxframeless/assets/13702789/8232b70c-460a-4296-86fa-7e0b4a8c74a4

抱歉，这么久才回复消息，我重新拉取了代码测试，问题还是一样，上面的连接是测试录像；

**测试环境:**
QT 版本: qt 6.5 win11 23H2

**如果禁用 QX_FRAMELESS_CONFIG_NATIVE 则正常**
